# Generated by Django 2.0 on 2018-01-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='devices_phone',
            fields=[
                ('deviceName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('platformName', models.CharField(max_length=30)),
                ('platformVersion', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
            ],
        ),
    ]
