# Generated by Django 2.0 on 2018-01-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_platform', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices_phone',
            name='id',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
