# Generated by Django 2.0 on 2018-01-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_platform', '0003_devices_phone_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
