# Generated by Django 2.0 on 2018-01-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_platform', '0004_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_project',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=30)),
                ('project_address', models.CharField(max_length=30)),
            ],
        ),
    ]
