# Generated by Django 2.0 on 2018-01-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_platform', '0008_auto_20180118_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools_name', models.CharField(max_length=30)),
                ('tools_address', models.CharField(max_length=30)),
            ],
        ),
    ]
