# Generated by Django 2.0 on 2018-01-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_platform', '0011_auto_20180119_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject_show_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
