# Generated by Django 2.0 on 2018-01-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_platform', '0013_auto_20180124_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_report',
            name='App_version',
            field=models.CharField(default=4.1, max_length=30),
            preserve_default=False,
        ),
    ]
