# Generated by Django 2.0 on 2018-01-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_platform', '0014_my_report_app_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='case_warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('api_name', models.CharField(max_length=50)),
                ('case_name', models.CharField(max_length=50)),
                ('case_address', models.CharField(max_length=255)),
            ],
        ),
    ]
