# Generated by Django 2.0 on 2018-01-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_platform', '0015_case_warehouse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='case_warehouse',
            new_name='my_case',
        ),
    ]
