# Generated by Django 2.0 on 2018-01-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_platform', '0016_auto_20180125_1654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='my_case',
            new_name='my_case_of_API',
        ),
    ]
