# Generated by Django 2.0 on 2018-01-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_platform', '0017_auto_20180125_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_uuid', models.CharField(max_length=30)),
                ('task_state', models.IntegerField(max_length=3)),
                ('task_type', models.CharField(max_length=30)),
                ('task_data', models.TextField()),
            ],
        ),
    ]
