# Generated by Django 2.0 on 2018-01-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_platform', '0018_task_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_case_of_api',
            name='case_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='my_report',
            name='report_data',
            field=models.TextField(),
        ),
    ]
