# Generated by Django 2.0 on 2018-01-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_platform', '0019_auto_20180126_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_management',
            name='task_state',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task_management',
            name='task_uuid',
            field=models.CharField(max_length=100),
        ),
    ]
