# Generated by Django 2.0 on 2018-01-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_platform', '0020_auto_20180126_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_management',
            name='task_project',
            field=models.CharField(default=111, max_length=30),
            preserve_default=False,
        ),
    ]
