# Generated by Django 2.0 on 2018-01-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_platform', '0021_task_management_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_management',
            name='create_time',
            field=models.DateField(auto_now=True),
        ),
    ]
