# Generated by Django 2.0 on 2018-01-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_platform', '0022_task_management_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_report',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task_management',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
