# Generated by Django 2.0 on 2018-01-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_platform', '0027_my_case_of_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_case_of_text',
            name='revise_type',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
