# Generated by Django 2.0 on 2018-01-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_platform', '0028_my_case_of_text_revise_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=300)),
                ('user_password', models.CharField(max_length=300)),
            ],
        ),
    ]
