# Generated by Django 2.0 on 2018-02-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_platform', '0030_auto_20180205_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_case_of_UI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('module_name', models.CharField(max_length=30)),
                ('case_name', models.CharField(max_length=100)),
                ('case_address', models.CharField(max_length=255)),
                ('App_version', models.CharField(max_length=255)),
                ('my_case_of_text_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='my_case_of_api',
            name='my_case_of_text_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
