# Generated by Django 2.0 on 2018-03-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_platform', '0033_course_subject_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='pad_pesourceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=300)),
                ('json_data', models.TextField()),
            ],
        ),
    ]
